### ISSUE TITLE
Nginx fails when the registry/controller response body is too large

### ISSUE THREAD

**Issue by zachidan** [amalgam8/amalgam8#309]
In case the request body is larger than the memory buffer (defined by the client_body_buffer_size nginx directive), the whole body or only its part is written to a temporary file.
In such a case, a special lua code is required to read the data from the file and handle it properly.

The symptoms of this issue are several errors in nginx. For example:

level=error msg="POST to NGINX server failed" body="error decoding input json: bad argument #1 to '?' (string expected, got nil)\n" status_code=400 
level=error msg="Failed to update HTTP upstreams with NGINX" error="nginx: POST to NGINX server failed"

**Comment by rshriram** [comment]
Do you have an example of the message body, so that I can replicate the issue on my end?

**Comment by zachidan** [comment]
By default, buffer size is equal to two memory pages. It is usually 16K on 64-bit platforms (see [client_body_buffer_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size)

I used the eureka remote catalog with the Watson-DEV data to reproduce the problem, but any data that is larger than 16K can be used to reproduce the problem.

**Comment by zachidan** [comment]
@rshriram Can you handle this issue ?

**Comment by rshriram** [comment]
The problem is not with client_body_buffer_size. Its that the JSON is bigger than 1mb, which is more than the default client_max_body_size parameter (1Mb). http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

A simple fix is to disable the size field for the admin location block, which is okay since its not exposed externally.
