### ISSUE TITLE
Rules DSL: support path prefix and host header based destinations

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#367]
Currently, the controller rules DSL supports specifying destinations with service names only, with the expectation that the user would be accessing the sidecar via the URL http://localhost:6379/<destination>/api.

It needs to support additional forms of specifying the destination namely:
path prefixes: /api/v1/ratings/
host headers: 
```bash
GET / HTTP/1.1
Host: ratings.mybookstore.local
```
In the host header case, the destination is actually empty (or can be extracted from the host header).

It would be good to have a destination of the form:

```json
destination: {
 "name": "ratings" [mandatory]
 "host" : "ratings.mybookstore.local",
 "path" : "/api/v1/ratings"
}
```
where destination should have name and atleast one of host or path should be present.

**Comment by frankbu** [comment]
I think I understand the requirement, but I'm wondering if extending the destination field is the right way to handle it. In my mind, the destination that the rule is referring to is just a service (e.g., "ratings"). A separate question is how we can tell when the destination is being called: is it some kind of path pattern or host header? I don't think the answer to that question changes the destination. 

Currently, we have a default answer built into the code. If we allow this to be changed, I wonder if it's really a per-rule configuration, or if it's even necessary to allow more than 1 answer. In other words, would it make sense to say that calls to the ratings service via a host header should go to v1, while calls via a path should go to v2. Maybe we just need a way to configure how services are identified (e.g., host or path) in one place (special rule?), instead of repeating it in every rule.

**Comment by rshriram** [comment]
That's a good point. To keep things simple, we could have a single destination config rule.
I wonder if we could apply the same principle to other aspects of the rule.

**Comment by ijsnellf** [comment]
We can already support the host based routing. `Host` is just a header, so the rule just needs to include the following inside the match:
```json
"match": {
  "headers": {
    "Host": "ratings.mybookstore.local"
  }
},
```
The path option will require an additional field. I believe the most logical place for this field would be inside the match definition:
```json
"match": {
  "path": "/api/v1/ratings"
},
```
Opinions? @rshriram @frankbu

**Comment by rshriram** [comment]
Path and prefix. As envoy supports both.

**Comment by ijsnellf** [comment]
There is an issue that prevents routing via the `Host` header. A match like the following will not route properly:
```json
"match": {
  "headers": {
    "Host": "www.example.org"
  }
},
```
Any other header works.

**Comment by jemcginn** [comment]
P1 - Needed for bookinfo

**Comment by GregHanson** [comment]
so in order to support matching on Host header, the rule needs to be created to match on the `:authority` header.  For example:
```yaml
rules:
- priority: 1
  destination: reviews
  match:
    headers:
      ":authority": "my_header_value"
  route:
    backends:
    - tags:
      - version=v3
```

This rule would match for `curl -i localhost:32000/reviews/health -H "Host: my_header_value"`
