### ISSUE TITLE
Support K8S Third Party Resource rules configuration via A8CTL

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#530]
Currently there are separate instructions for configuring rules in Amalgam8 depending upon whether running in K8S environment vs. non-K8S environment.  This item is for having the backend support of A8CTL drive the Third Party Resource configuration in K8S.  

This item also will require the deployment descriptor modification so that the A8 rules controller can be stood up in a K8S environment.

**Comment by elevran** [comment]
amalgam8 rules can be programmed directly to k8s using kubectl and thirdparty resources. We'd like to implement a k8s variant where rules are accessed using a8ctl through the rules-controller, but storage is delegated to k8s TPRs. Pulling from the sidecars is always via TPR's in k8s - so only the upstream flow is changed. This also enables in-band verification of rule syntx, etc.

https://github.com/amalgam8/amalgam8/tree/master/controller/rules has memory and redis backends. The requirement is to add k8s TPRs as another storage option when deploying on Kubernetes, so the rules.Manager interface needs to be implemented by a new backend.

The new implementation would replace the k8srules controller as well, since it will mark rules as "valid" when received or reject them when not. However, it means that it needs to take on some if it's responsibility as well (e.g., ensuring the TPR is registered).
We will not support a mixed mode (rules posted also using kubectl, in which case it needs to read and validate the rule and update the status). This is lower priority, if needed at all.

Code for creating a k8s client and accessing TPR's can be imported from cmd/k8srules, possibly with some refactoring.
Also, a corresponding deployment yaml should be provided (similar to k8s-controlplane.yaml)

**Comment by GregHanson** [comment]
These are the options:

1. Modify controller to talk to k8s for storing rules (currently pursuing)
    1. a8ctl CLI still won't have full functionality because service-list command only knows how to talk to a8registry
       1. pretty sure a8registry has a k8s adapter for getting services, would need to add the a8registry to controlplane yamls
    1. current controller API supports atomic bulk operations and k8s TPR's are only atomic by resource:
       1. do we modify the controller API to no longer support bulk operations?
          1. will need to modify all rule .yaml files to no longer be bulk and update demo doc steps
       1. do we modify the controller API to report status of by resource atomic operations similar to what cloudant does

1. Modify a8ctl to talk directly to k8s TPRs
     1. a8ctl needs to dynamically know whether to call controller/registry urls or k8s
        1. refactoring of a8ctl code required to use k8s adapters
        1. modify a8ctl docs with new config options for k8s support
     1. No uniform rules API between docker and k8s

1. Modify and maintain separate docs for a8 on docker and k8s

**Comment by ijsnellf** [comment]
Resolved (in large part) by https://github.com/amalgam8/amalgam8/pull/534.
