### ISSUE TITLE
Question: What ist the status of this project?

### ISSUE THREAD

**Issue by nrekretep** [amalgam8/amalgam8#560]
Hi there, 

could anybody please give a short update about the status of this project?

At least the website amalgam8.github.io redirects to a suspect website which offers content which has clearly nothing to do with this project. 

Please be kind and inform your community about the current status.

Thanks!

**Comment by GregHanson** [comment]
Hi @nrekretep, it would definitely appear that the original redirect we had in place has expired - sorry about that. You should have been redirected to https://istio.io .  After deciding to collaborate with Google and RedHat on a more verbose proxy solution, we decided to start with a new project and repo since incorporating the additional features would have meant a significant overhaul of the existing code.  https://github.com/istio/istio is still going strong and there is an active community of developers and users.  If you have any questions the istio.io website is a great place to start (the bookinfo example is still around: https://istio.io/docs/examples/bookinfo/), or you can post to one of the google-groups here: https://istio.io/about/community/

**Comment by nrekretep** [comment]
Hello Greg,

thanks for the information and for updating the README. 
I will definitely look into istio.
